import Head from "next/head";
import Description from "../components/Description";
import Header from "../components/Header";
import RaffleEntrance from "../components/RaffleEntrance";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="grid grid-cols-2 h-full">
        <Description />
        <RaffleEntrance />
      </div>
    </div>
  );
}
